### ISSUE TITLE
Company name and logo overlays screen content upon scrolling

### ISSUE THREAD

**Issue by nickolashe** [dannypernik/agency#2]

**Comment by nickolashe** [comment]
https://ibb.co/Df5pWML

**Comment by dannypernik** [comment]
> https://ibb.co/Df5pWML

Link doesn't work for me. But I assume you're referring to this:

![image](https://user-images.githubusercontent.com/3347095/217677870-4bbd2e9a-df1e-4e38-a94c-006a8105aef0.png)
